site_name: Animuspedia

copyright: Copyright &copy; 2014 - 2022 Animus Projesi

# Theme
theme:
    name: 'material'
    language: tr
    favicon: Görseller/Site3.webp
    logo: Görseller/Site3.webp
    
    features:
      - navigation.tabs
      - navigation.top
      
    palette:
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: orange

# Extensions
markdown_extensions:
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - meta
  - tables
  - md_in_html
  - admonition
  - pymdownx.details
  
plugins:
  - search
  - roamlinks 
  - tags
  
extra_css:
  - stylesheets/extra.css